name: Create VPC

on:
  workflow_run:
    workflows: ["Validate VPC"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  wait-for-approval:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment: dev # Approval is needed for all envs.

    steps:
      - name: Awaiting manual approval
        run: echo "Approval granted, proceeding to apply..."

  apply-changes:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
          aws-region: us-west-2

      - name: Apply changes
        run: |
          terraform -chdir=env/dev/us-west-2/vpc init
          terraform -chdir=env/dev/us-west-2/vpc apply -auto-approve
