name: Destruction

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
          aws-region: us-east-1

      - name: Apply changes
        run: |
          terraform -chdir=env/dev/us-east-1/resources/vpc init
          terraform -chdir=env/dev/us-east-1/resources/vpc destroy -auto-approve

