name: Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
          aws-region: us-west-2

      - name: Download Statefile
        run: aws s3 cp  s3://remote-backend-for-tf/env/dev/us-west-2/resources/vpc/terraform.tfstate env/dev/us-west-2/resources/vpc/terraform.tfstate
     
      - name: Destroy Terraform Resources
        run: |
          terraform -chdir=env/dev/us-west-2/resources init
          terraform -chdir=env/dev/us-west-2/resources destroy  -auto-approve
