name: Destroy

on:
  workflow_dispatch:
  inputs:
    resource_name:
      required: true
      type: string
      description: "Confirm the resource to be destroyed"

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Download Terraform State
        uses: actions/download-artifact@v4
        with:
          name: terraform-state

      - name: Destroy Terraform Resources
        run: |
          terraform -chdir=env/dev/us-east-1/resources/vpc init
          terraform -chdir=env/dev/us-east-1/resources/vpc destroy -target=module."${{ inputs.resource_name }}" -auto-approve

