name: Destroy Customer-01

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
          aws-region: us-west-2

      - name: Destroy Terraform Resources
        env:
          TF_VAR_public_key: ${{ secrets.EKS_PUBLIC_KEY }}
        run: |
          terraform -chdir=env/dev/us-west-2/customer-01 init
          terraform -chdir=env/dev/us-west-2/customer-01 destroy  -auto-approve
