name: Destroy

on:
  workflow_dispatch:
    inputs:
      resource_name:
        required: true
        type: choice
        default: "vpc"
        description: "Confirm the resource to be destroyed"
        options:
          - vpc
          - eks
          - node-group

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        dir:
          - "env/dev/us-east-1/resources/vpc"
          - "env/dev/us-east-1/resources/eks"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
          aws-region: us-east-1

      - name: Download Statefile
        run: aws s3 cp  s3://remote-backend-for-tf/env/dev/us-east-1/resources/vpc/terraform.tfstate env/dev/us-east-1/resources/vpc/terraform.tfstate
     
      - name: Destroy Terraform Resources
        run: |
          terraform -chdir=${{ matrix.dir }} init
          terraform -chdir=${{ matrix.dir }} destroy -target=module."${{ inputs.resource_name }}" -auto-approve

