name: Apply

on:
  workflow_run:
    workflows: ["Validation"]
    types:
      - completed

jobs:
  wait-for-approval:
    runs-on: ubuntu-latest
    environment: dev # Approval is needed for all envs.

    steps:
      - name: Awaiting manual approval
        run: echo "Approval granted, proceeding to apply..."

  apply-changes:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply changes
        run: |
          terraform -chdir=env/dev/us-east-1/resources/vpc apply -auto-approve

