name: Terraform Lint

on:
  push:
    branches:
      - main
  #pull_request:
  #  branches:
  #    - main

jobs:
  lint:
    name: Lint Terraform Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Check Terraform Formatting
        run: terraform fmt -recursive

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: check dir
        run: ls && pwd
        
      - name: Run TFLint
        run: |
          tf_files=`find . -iname '*.tf'`
          for i in $tf_files; do
            tflint --config=$i
          done
