name: Provision Remote Backend

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "remote-backend-resource/**"

permissions:
  id-token: write
  contents: read  

jobs:
  provision-remote-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      #- name: Configure AWS creds
      #  uses: aws-actions/configure-aws-credentials@v4
      #  with:
      #    role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
      #    aws-region: us-west-2

      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Validate & Plan
        run: |
          terraform -chdir=remote-backend-resource init
          terraform -chdir=remote-backend-resource validate
          terraform -chdir=remote-backend-resource plan
          terraform -chdir=remote-backend-resource apply -auto-approve

      - name: Push Statefile to S3
        run: aws s3 cp remote-backend-resource/terraform.tfstate s3://terraform-remote-be-bucket/remote/terraform.tfstate
