name: Terraform Lint & Validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-lint-validate:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Check Terraform Formatting
        run: terraform fmt -check -recursive

      - name: Validate Terraform
        run: terraform validate
    
      - name: Terraform Plan
        run: terraform plan -out=tfplan
  
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan
