name: Terraform Validate & Plan

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-validate-plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      #- name: Find Terraform Directories
      #  id: find-dirs
      #  run: |
      #    echo "directories=$(find modules -type f -name 'main.tf' -exec dirname {} \; | sort | uniq | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

      - name: Validate & Plan
        run: |
          terraform -chdir=env/dev/us-east-1/resources/vpc init
          terraform -chdir=env/dev/us-east-1/resources/vpc validate
          terraform -chdir=env/dev/us-east-1/resources/vpc plan -out=tfplan
