name: Validate VPC

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "env/dev/us-west-2/vpc/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-validate-plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::014337110715:role/github-actions-role
          aws-region: us-west-2

      - name: Validate & Plan
        run: |
          terraform -chdir=env/dev/us-west-2/vpc init
          terraform -chdir=env/dev/us-west-2/vpc validate
          terraform -chdir=env/dev/us-west-2/vpc plan
